name: Food_Khan
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  provider: ^6.1.4
  flutter_swiper_view: ^1.1.8
  curved_navigation_bar: ^1.0.6
  avatar_glow: ^3.0.1
  glass_kit: ^4.0.1
  firebase_core: ^3.13.0
  firebase_core_web: ^2.22.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  fluttertoast: ^8.2.12
  country_picker: ^2.0.27
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0

flutter_launcher_icons:
  
  android: true
  ios: true
  image_path: "lib/asset/image/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/asset/image/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/asset/font/Roboto_Condensed-Medium.ttf
  #     - asset: fonts/Schyler-Italic.ttf