name: food_khan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_core_web: ^2.22.0
  
  # Supabase
  supabase_flutter: ^2.10.3

  # State Management
  get: ^4.7.2
  provider: ^6.1.4

  # UI & Animations
  avatar_glow: ^3.0.1
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter_animate: ^4.5.2
  flutter_swiper_view: ^1.1.8
  font_awesome_flutter: ^10.8.0
  glass_kit: ^4.0.1
  google_fonts: ^6.3.1

  # Utility
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/asset/image/appLogo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/asset/image/
    - lib/asset/image/bank_card/
    - lib/asset/image/category/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: lib/asset/font/Roboto_Condensed-Medium.ttf
